//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class brugaelEntities : DbContext
    {
        public brugaelEntities()
            : base("name=brugaelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administradores> administradores { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<funcionarios> funcionarios { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<produtos> produtos { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
    }
}
